services:

  db:
    image: neo4j:5.26.4
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - "dbdata:/data"
      - "dblogs:/logs"
    # ports:
    #   - "7474:7474"
    #   - "7687:7687"
    healthcheck:
      test: perl -MIO::Socket::INET -e 'exit(! defined( IO::Socket::INET->new("localhost:7687")))'

  api:
    image: schi11er/datacat:${DATACAT_VERSION}
    restart: unless-stopped
    environment:
      - logging.level.de.bentrm=INFO
      - datacat.client.url=${DATACAT_EDITOR_URL}
      - datacat.auth.secret=${DATACAT_SECRET}
      - datacat.auth.issuer=${DATACAT_ISSUER}
      - datacat.users.admin.password=${DATACAT_ADMIN_PASSWORD}
      - spring.mail.port=${MAIL_PORT}
      - spring.mail.host=${MAIL_HOST}
      - spring.neo4j.authentication.username=neo4j
      - spring.neo4j.authentication.password=${NEO4J_PASSWORD}
      - spring.neo4j.uri=bolt://db:7687
      - management.health.mail.enabled=false
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: [
        "wait-for-it", "db:7687", "--timeout=300", "--",
        "wait-for-it", "${MAIL_HOST}:${MAIL_PORT}", "--timeout=30", "--",
        "java", "--enable-preview", "org.springframework.boot.loader.launch.JarLauncher" ]

  web:
    build:
      context: "./services/proxy/"
      args:
        VERSION: ${DATACAT_EDITOR_VERSION}
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - ${DATACAT_PORT:-3000}:80

  restapi:
    image: schi11er/datacatrestapi:${DATACAT_REST_API_VERSION}
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - ${DATACAT_REST_API_PORT:-3001}:3001
    environment:
      # - custom.server-url=http://api:8080 # for local development
      - custom.server-url=${DATACAT_EDITOR_URL}
      - custom.username=admin
      - custom.password=${DATACAT_ADMIN_PASSWORD}
      - springdoc.swagger-ui.path=/swagger-ui.html
      - server.forward-headers-strategy=framework
      - server.servlet.context-path=/api/e1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${DATACAT_REST_API_PORT:-3001}/swagger-ui/index.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  dbdata:
  dblogs:
